os:
  - linux
  - osx

language:
  - bash

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ucspi-tcp bash; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get install ucspi-tcp; fi
  - sudo easy_install bashtest
  - chmod +x ./bashttpd.sh
  - chmod +x ./tests/execute_tests.sh
  
before_script:
  - type tcpserver
  - type bashtest
  
script:
  - ./bashttpd.sh start
  - ./tests/execute_tests.sh
