os:
  matrix:
    - linux
    - osx

language:
  - bash

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ucspi-tcp; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install ucspi-tcp; fi
  - easy_install bashtest
  - chmod +x ./bashttpd.sh

script:
  - which tcpserver
  - tcpserver -c 10 127.0.0.1 2274 ./bashttpd.sh &
  - bashtest ./tests/serve_file.bashtest
  - bashtest ./tests/serve_dir_list.bashtest

