os:
  - osx

language:
  - bash

before_script:
  - brew update
  - easy_install bashtest
  - chmod +x ./bashttpd.sh
  - brew install ucspi-tcp

script:
  - which tcpserver
  - tcpserver -c 10 127.0.0.1 2274 ./bashttpd.sh &
  - bashtest ./tests/serve_file.bashtest
  - bashtest ./tests/serve_dir_list.bashtest

