sudo: required

os:
  - linux
  - osx

services:
  - docker

language:
  - bash

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get update;
      docker pull centos/centos:latest;
      docker run -d -p 127.0.0.1:2274:2274 centos:latest \
      /bin/sh -c "cd ~; git clone https://github.com/AjankeFoundation/bashttpd.git;"; 
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ucspi-tcp; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get install ucspi-tcp; fi
  - sudo easy_install bashtest
  - chmod +x ./bashttpd.sh
  
before_script:
  - which tcpserver
  - which bashtest

script:
  - tcpserver -c 10 127.0.0.1 2274 ./bashttpd.sh &
  - bashtest ./tests/serve_file.bashtest
  - bashtest ./tests/serve_dir_list.bashtest

