os:
  - linux
  - osx

language:
  - bash

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ucspi-tcp bash; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then sudo apt-get install ucspi-tcp; fi
  - sudo easy_install bashtest
  - chmod +x ./bashttpd.sh
  - chmod +x ./execute_tests.sh
  
before_script:
  - type tcpserver
  - type bashtest
  
script:
  - ./bashttpd.sh start
  - bashtest ./tests/start-tests/start_bashttpd_fail.bashtest
  - ./execute_tests.sh
  - ./bashttpd stop
  - bashtest ./tests/stop-tests/stop_bashttpd_fail.bashtest
